In [0]:
import tensorflow as tf
import matplotlib.pyplot as plt
import io
import pandas as pd

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
path = "/content/drive/My Drive/Colab Notebooks/FINAL_FROM_DF.csv"
final_stocks = pd.read_csv(path)

In [0]:
final_stocks

            SYMBOL SERIES      OPEN  ...   TIMESTAMP  TOTALTRADES          ISIN
0        20MICRONS     EQ     37.80  ...  2017-06-28          202  INE144J01027
1       3IINFOTECH     EQ      4.10  ...  2017-06-28         7353  INE748C01020
2          3MINDIA     EQ  13425.15  ...  2017-06-28          748  INE470A01017
3          63MOONS     EQ     61.00  ...  2017-06-28          437  INE111B01023
4          8KMILES     EQ    546.10  ...  2017-06-28         1866  INE650K01021
...            ...    ...       ...  ...         ...          ...           ...
846399        ZOTA     SM    221.00  ...  2017-12-29           14  INE358U01012
846400       ZUARI     EQ    562.00  ...  2017-12-29         2218  INE840M01016
846401   ZUARIGLOB     EQ    255.50  ...  2017-12-29         2001  INE217A01012
846402   ZYDUSWELL     EQ   1038.00  ...  2017-12-29         1401  INE768C01010
846403       ZYLOG     EQ      4.30  ...  2017-12-29          845  INE225I01026

[846404 rows x 13 columns]

In [0]:
final_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846404 entries, 0 to 846403
Data columns (total 13 columns):
SYMBOL         846404 non-null object
SERIES         843947 non-null object
OPEN           846404 non-null float64
HIGH           846404 non-null float64
LOW            846404 non-null float64
CLOSE          846404 non-null float64
LAST           846404 non-null float64
PREVCLOSE      846404 non-null float64
TOTTRDQTY      846404 non-null int64
TOTTRDVAL      846404 non-null float64
TIMESTAMP      846404 non-null object
TOTALTRADES    846404 non-null int64
ISIN           846404 non-null object
dtypes: float64(7), int64(2), object(4)
memory usage: 83.9+ MB

In [0]:
f_update = final_stocks.drop(["SERIES","ISIN"],axis=1)

In [0]:
f_update.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846404 entries, 0 to 846403
Data columns (total 11 columns):
SYMBOL         846404 non-null object
OPEN           846404 non-null float64
HIGH           846404 non-null float64
LOW            846404 non-null float64
CLOSE          846404 non-null float64
LAST           846404 non-null float64
PREVCLOSE      846404 non-null float64
TOTTRDQTY      846404 non-null int64
TOTTRDVAL      846404 non-null float64
TIMESTAMP      846404 non-null object
TOTALTRADES    846404 non-null int64
dtypes: float64(7), int64(2), object(2)
memory usage: 71.0+ MB

In [0]:
y1 = f_update["CLOSE"]

In [0]:


corr = f_update.corr()
corr

                 OPEN      HIGH       LOW  ...  TOTTRDQTY  TOTTRDVAL  TOTALTRADES
OPEN         1.000000  0.999887  0.999906  ...  -0.031836   0.060235     0.022101
HIGH         0.999887  1.000000  0.999818  ...  -0.031754   0.060912     0.022765
LOW          0.999906  0.999818  1.000000  ...  -0.031861   0.059863     0.021678
CLOSE        0.999836  0.999917  0.999902  ...  -0.031768   0.060530     0.022334
LAST         0.999743  0.999830  0.999808  ...  -0.031744   0.060451     0.022429
PREVCLOSE    0.999164  0.999111  0.999081  ...  -0.031874   0.060044     0.022086
TOTTRDQTY   -0.031836 -0.031754 -0.031861  ...   1.000000   0.447041     0.475124
TOTTRDVAL    0.060235  0.060912  0.059863  ...   0.447041   1.000000     0.856671
TOTALTRADES  0.022101  0.022765  0.021678  ...   0.475124   0.856671     1.000000

[9 rows x 9 columns]

In [0]:
incomplete = f_update[f_update.isnull().any(axis=1)]
incomplete

Empty DataFrame
Columns: [SYMBOL, OPEN, HIGH, LOW, CLOSE, LAST, PREVCLOSE, TOTTRDQTY, TOTTRDVAL, TIMESTAMP, TOTALTRADES]
Index: []

In [0]:
f_cat = f_update["SYMBOL"]
f_encoded,f_categories = f_cat.factorize()

In [0]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
arr = encoder.fit_transform(f_encoded.reshape(-1,1))
arr

<846404x2037 sparse matrix of type '<class 'numpy.float64'>'
	with 846404 stored elements in Compressed Sparse Row format>

In [0]:
f_update = f_update.drop("SYMBOL",axis=1)

In [0]:
f_update

            OPEN      HIGH       LOW  ...    TOTTRDVAL   TIMESTAMP  TOTALTRADES
0          37.80     37.80     36.15  ...    994657.90  2017-06-28          202
1           4.10      4.85      4.00  ...  92148517.65  2017-06-28         7353
2       13425.15  13469.55  12920.00  ...  30304923.35  2017-06-28          748
3          61.00     61.90     60.35  ...   1689421.00  2017-06-28          437
4         546.10    548.00    535.00  ...  43208620.05  2017-06-28         1866
...          ...       ...       ...  ...          ...         ...          ...
846399    221.00    221.00    214.00  ...   3041550.00  2017-12-29           14
846400    562.00    562.00    549.55  ...  58163061.60  2017-12-29         2218
846401    255.50    258.40    252.50  ...  22968100.60  2017-12-29         2001
846402   1038.00   1068.00   1033.00  ...  29938840.10  2017-12-29         1401
846403      4.30      5.15      4.30  ...   3495213.70  2017-12-29          845

[846404 rows x 10 columns]

In [0]:
arr = arr.toarray()

In [0]:
f_update = f_update.drop("CLOSE",axis=1)
f_update

            OPEN      HIGH       LOW  ...    TOTTRDVAL   TIMESTAMP  TOTALTRADES
0          37.80     37.80     36.15  ...    994657.90  2017-06-28          202
1           4.10      4.85      4.00  ...  92148517.65  2017-06-28         7353
2       13425.15  13469.55  12920.00  ...  30304923.35  2017-06-28          748
3          61.00     61.90     60.35  ...   1689421.00  2017-06-28          437
4         546.10    548.00    535.00  ...  43208620.05  2017-06-28         1866
...          ...       ...       ...  ...          ...         ...          ...
846399    221.00    221.00    214.00  ...   3041550.00  2017-12-29           14
846400    562.00    562.00    549.55  ...  58163061.60  2017-12-29         2218
846401    255.50    258.40    252.50  ...  22968100.60  2017-12-29         2001
846402   1038.00   1068.00   1033.00  ...  29938840.10  2017-12-29         1401
846403      4.30      5.15      4.30  ...   3495213.70  2017-12-29          845

[846404 rows x 9 columns]

In [0]:
da = pd.DataFrame(arr,columns=f_categories)

In [0]:
dateme = f_update["TIMESTAMP"].values

In [0]:
f_update = f_update.drop("TIMESTAMP",axis=1)

In [0]:
upd = pd.DataFrame()
upd = f_update.loc[0:99999, :]
upd

           OPEN      HIGH       LOW  ...  TOTTRDQTY     TOTTRDVAL  TOTALTRADES
0         37.80     37.80     36.15  ...      27130  9.946579e+05          202
1          4.10      4.85      4.00  ...   20157058  9.214852e+07         7353
2      13425.15  13469.55  12920.00  ...       2290  3.030492e+07          748
3         61.00     61.90     60.35  ...      27701  1.689421e+06          437
4        546.10    548.00    535.00  ...      79722  4.320862e+07         1866
...         ...       ...       ...  ...        ...           ...          ...
99995    900.00    910.00    875.00  ...        363  3.199389e+05           41
99996      7.80      7.90      7.65  ...      10991  8.515220e+04           68
99997    161.45    162.55    160.00  ...    3031001  4.898383e+08        21589
99998   1125.10   1146.00   1100.00  ...       1000  1.128860e+06           11
99999   1295.00   1295.00   1290.00  ...        238  3.072600e+05            6

[100000 rows x 8 columns]

In [0]:
ar = da.loc[0:99999,:]
ar
upd = upd.join(ar)

In [0]:
upd

           OPEN      HIGH       LOW  ...  CLUTCHAUTO  ASTRON  SGBDEC2512
0         37.80     37.80     36.15  ...         0.0     0.0         0.0
1          4.10      4.85      4.00  ...         0.0     0.0         0.0
2      13425.15  13469.55  12920.00  ...         0.0     0.0         0.0
3         61.00     61.90     60.35  ...         0.0     0.0         0.0
4        546.10    548.00    535.00  ...         0.0     0.0         0.0
...         ...       ...       ...  ...         ...     ...         ...
99995    900.00    910.00    875.00  ...         0.0     0.0         0.0
99996      7.80      7.90      7.65  ...         0.0     0.0         0.0
99997    161.45    162.55    160.00  ...         0.0     0.0         0.0
99998   1125.10   1146.00   1100.00  ...         0.0     0.0         0.0
99999   1295.00   1295.00   1290.00  ...         0.0     0.0         0.0

[100000 rows x 2045 columns]

In [0]:
cols = upd.columns
cols

Index(['OPEN', 'HIGH', 'LOW', 'LAST', 'PREVCLOSE', 'TOTTRDQTY', 'TOTTRDVAL',
       'TOTALTRADES', '20MICRONS', '3IINFOTECH',
       ...
       'CRMFCP6RG', 'SDAFIIIGR', 'BSLFTPLVDG', 'IPRU2262', 'SMCSRIIIRD',
       'ICICI0801', 'ICICI0901', 'CLUTCHAUTO', 'ASTRON', 'SGBDEC2512'],
      dtype='object', length=2045)

In [0]:
import numpy as np
aray = np.array(upd)

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
aray = scaler.fit_transform(aray)
aray

array([[-0.25054987, -0.25163343, -0.25065664, ...,  0.        ,
         0.        ,  0.        ],
       [-0.26515169, -0.26578336, -0.26473338, ...,  0.        ,
         0.        ,  0.        ],
       [ 5.55003619,  5.51645067,  5.39048203, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.19697373, -0.19806122, -0.19642945, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.22056482,  0.22426813,  0.21514554, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.29418055,  0.28825418,  0.29833623, ...,  0.        ,
         0.        ,  0.        ]])

In [0]:
fra = pd.DataFrame(aray,columns=cols)
fra

           OPEN      HIGH       LOW  ...  CLUTCHAUTO  ASTRON  SGBDEC2512
0     -0.250550 -0.251633 -0.250657  ...         0.0     0.0         0.0
1     -0.265152 -0.265783 -0.264733  ...         0.0     0.0         0.0
2      5.550036  5.516451  5.390482  ...         0.0     0.0         0.0
3     -0.240498 -0.241284 -0.240061  ...         0.0     0.0         0.0
4     -0.030309 -0.032535 -0.032237  ...         0.0     0.0         0.0
...         ...       ...       ...  ...         ...     ...         ...
99995  0.123032  0.122921  0.116630  ...         0.0     0.0         0.0
99996 -0.263549 -0.264474 -0.263135  ...         0.0     0.0         0.0
99997 -0.196974 -0.198061 -0.196429  ...         0.0     0.0         0.0
99998  0.220565  0.224268  0.215146  ...         0.0     0.0         0.0
99999  0.294181  0.288254  0.298336  ...         0.0     0.0         0.0

[100000 rows x 2045 columns]

In [0]:
upd = fra

In [0]:
y_upd = y1[:100000]
y_upd = y_upd.values

In [0]:
y_upd1 = y_upd.reshape(-1,1)
y_upd1 = scaler.fit_transform(y_upd1)

In [0]:
y_upd1 = y_upd1.flatten()
y_upd1

array([-0.25116966, -0.26518033,  5.48750368, ..., -0.19681864,
        0.22968283,  0.29240555])

In [0]:
valOfDate = pd.DataFrame(dateme,columns=["TIMESTAMP"])
f_update = f_update.join(valOfDate)
f_update

            OPEN      HIGH       LOW  ...    TOTTRDVAL  TOTALTRADES   TIMESTAMP
0          37.80     37.80     36.15  ...    994657.90          202  2017-06-28
1           4.10      4.85      4.00  ...  92148517.65         7353  2017-06-28
2       13425.15  13469.55  12920.00  ...  30304923.35          748  2017-06-28
3          61.00     61.90     60.35  ...   1689421.00          437  2017-06-28
4         546.10    548.00    535.00  ...  43208620.05         1866  2017-06-28
...          ...       ...       ...  ...          ...          ...         ...
846399    221.00    221.00    214.00  ...   3041550.00           14  2017-12-29
846400    562.00    562.00    549.55  ...  58163061.60         2218  2017-12-29
846401    255.50    258.40    252.50  ...  22968100.60         2001  2017-12-29
846402   1038.00   1068.00   1033.00  ...  29938840.10         1401  2017-12-29
846403      4.30      5.15      4.30  ...   3495213.70          845  2017-12-29

[846404 rows x 9 columns]

In [0]:
f_update = f_update.drop("TIMESTAMP",axis=1)

In [0]:

upd

           OPEN      HIGH       LOW  ...  CLUTCHAUTO  ASTRON  SGBDEC2512
0     -0.250550 -0.251633 -0.250657  ...         0.0     0.0         0.0
1     -0.265152 -0.265783 -0.264733  ...         0.0     0.0         0.0
2      5.550036  5.516451  5.390482  ...         0.0     0.0         0.0
3     -0.240498 -0.241284 -0.240061  ...         0.0     0.0         0.0
4     -0.030309 -0.032535 -0.032237  ...         0.0     0.0         0.0
...         ...       ...       ...  ...         ...     ...         ...
99995  0.123032  0.122921  0.116630  ...         0.0     0.0         0.0
99996 -0.263549 -0.264474 -0.263135  ...         0.0     0.0         0.0
99997 -0.196974 -0.198061 -0.196429  ...         0.0     0.0         0.0
99998  0.220565  0.224268  0.215146  ...         0.0     0.0         0.0
99999  0.294181  0.288254  0.298336  ...         0.0     0.0         0.0

[100000 rows x 2045 columns]

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(upd,y_upd1,test_size=0.3,random_state=42)

In [0]:
from sklearn.linear_model import SGDRegressor
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.svm import LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
models = [
    SGDRegressor(),
    DecisionTreeRegressor(max_depth=5),
    RandomForestRegressor(n_estimators=10,random_state=42)
]

In [0]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
for model in models:
    model.fit(X_train.values,y_train)
    y_pred = model.predict(X_test.values)
    #plt.plot(y_test,  color='gray')
    #plt.plot(y_pred, color='red', linewidth=2)
    #plt.show()
    #print(mean_squared_error(y_pred,y_test))
    print(y_pred,y_test)

[ 2.35242736e+07  4.99087032e+08 -1.03426463e+09 ... -9.41963461e+08
 -2.26931712e+08 -1.09146722e+09] [-0.16944794 -0.14461478 -0.1101086  ...  0.14169318 -0.09401585
  0.1666131 ]
[-0.18577297 -0.10134172 -0.10134172 ...  0.18187159 -0.10134172
  0.18187159] [-0.16944794 -0.14461478 -0.1101086  ...  0.14169318 -0.09401585
  0.1666131 ]
[-0.16895201 -0.14442667 -0.10978152 ...  0.14127966 -0.09450905
  0.16659442] [-0.16944794 -0.14461478 -0.1101086  ...  0.14169318 -0.09401585
  0.1666131 ]

In [0]:
X_test

           OPEN      HIGH       LOW  ...  CLUTCHAUTO  ASTRON  SGBDEC2512
75721 -0.167423 -0.169139 -0.168079  ...         0.0     0.0         0.0
80184 -0.146626 -0.139894 -0.145836  ...         0.0     0.0         0.0
19864 -0.108605 -0.110907 -0.108379  ...         0.0     0.0         0.0
76699 -0.099679 -0.099226 -0.101658  ...         0.0     0.0         0.0
92991 -0.127843 -0.128815 -0.131300  ...         0.0     0.0         0.0
...         ...       ...       ...  ...         ...     ...         ...
42648 -0.174768 -0.176525 -0.177317  ...         0.0     0.0         0.0
86306 -0.266018 -0.266943 -0.265631  ...         0.0     0.0         0.0
45466  0.149029  0.145187  0.144302  ...         0.0     0.0         0.0
63724 -0.093006 -0.092055 -0.092704  ...         0.0     0.0         0.0
34122  0.166360  0.161570  0.171361  ...         0.0     0.0         0.0

[30000 rows x 2045 columns]

In [0]:

def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [0]:
n_steps=1
n_inputs=2045
n_layers = 3
n_neurons = 150
n_outputs=150
learning_rate =0.5
reset_graph()
X = tf.placeholder(tf.float32,[None,n_steps,n_inputs])
y = tf.placeholder(tf.int32,[None])
basic_cell = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,activation = tf.nn.relu) for layer in range(n_layers)]
multi_layer_cell = tf.contrib.rnn.MultiRNNCell(basic_cell)
outputs,states = tf.nn.dynamic_rnn(multi_layer_cell,X,dtype=tf.float32)
states_concat = tf.concat(axis=1,values = states)
logits = tf.layers.dense(states_concat,n_outputs)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits,labels=y)
loss = tf.reduce_mean(xentropy)
optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate)
training_ob = optimizer.minimize(loss)
correct = tf.nn.in_top_k(logits,y,1)
accuracy = tf.reduce_mean(tf.cast(correct,tf.float32))
init = tf.global_variables_initializer()

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From <ipython-input-42-36557536ab99>:10: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From <ipython-input-42-36557536ab99>:11: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From <ipython-input-42-36557536ab99>:12: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/rnn_cell_impl.py:456: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/rnn_cell_impl.py:460: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From <ipython-input-42-36557536ab99>:14: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.

In [0]:
def next_batch(num, data, labels):
    idx = np.arange(0 , len(data))
    np.random.shuffle(idx)
    idx = idx[:num]
    data_shuffle = np.asarray([data.iloc[i] for i in idx])
    labels_shuffle = np.asarray([labels[i] for i in idx])

    return data_shuffle, labels_shuffle

In [0]:
X_test1 = np.array(X_test)
X_test1.shape

(30000, 2045)

In [0]:
X_test2 = X_test1.reshape(30000,1,2045)

In [0]:
n_epochs = 10
batch_size = 1500

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(20):
            X_batch, y_batch = next_batch(batch_size,X_train,y_train)
            X_batch = X_batch.reshape((-1, n_steps, n_inputs))
            sess.run(training_ob, feed_dict={X: X_batch, y: y_batch})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch})
        acc_test = accuracy.eval(feed_dict={X: X_test2, y: y_test})
        
        print("Epoch", epoch, "Train accuracy =", acc_train, "Test accuracy =", acc_test)

Epoch 0 Train accuracy = 0.9486667 Test accuracy = 0.9428
Epoch 1 Train accuracy = 0.9726667 Test accuracy = 0.9764
Epoch 2 Train accuracy = 0.97533333 Test accuracy = 0.9758
Epoch 3 Train accuracy = 0.97333336 Test accuracy = 0.976
Epoch 4 Train accuracy = 0.9826667 Test accuracy = 0.97356665
Epoch 5 Train accuracy = 0.982 Test accuracy = 0.97546667
Epoch 6 Train accuracy = 0.9633333 Test accuracy = 0.96576667
Epoch 7 Train accuracy = 0.98066664 Test accuracy = 0.9756333
Epoch 8 Train accuracy = 0.974 Test accuracy = 0.9755
Epoch 9 Train accuracy = 0.9726667 Test accuracy = 0.9755

In [0]:
#X_batch, y_batch = next_batch(100,X_train.values,y_train)

In [0]:
#X_batch, y_batch = next_batch(100,X_train.values,y_train)
len(X_train)

70000

In [0]:
X_maybe = np.asarray([X_train.iloc[i] for i in range(10)])

In [0]:
X_batch.shape

(1500, 1, 2045)